[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pose_estimation_models"
readme = "README.md"
description = "Easily test and apply pairwise image matching models"
authors = [
  {name = "Gabriele Berton"},{email = "berton.gabri@gmail.com"},
  {name = "Gabriele Trivigno", email="gabriele.trivigno@polito.it"},
  {name = "Alex Stoken", email = "alex.stoken@gmail.com"},
]
maintainers = [
  {name = "Gabriele Berton"},{email = "berton.gabri@gmail.com"},
  {name = "Alex Stoken", email = "alex.stoken@gmail.com"},
]
requires-python = ">= 3.10"
license = {file = "LICENSE"}
keywords = ["image matching"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dynamic = ["version",
            "dependencies"]


[project.urls]
Homepage = "https://github.com/gmberton/image-matching-models"
# Documentation = "https://readthedocs.org"
Repository = "https://github.com/gmberton/image-matching-models"
# "Bug Tracker" = "https://github.com/me/spam/issues"
# Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[tool.setuptools.dynamic]
dependencies = { file = [
  "./requirements.txt",
] }
version = { attr = "matching.__version__" }

[tool.setuptools.packages]
find = {}

[project.optional-dependencies]
silk = [
        "hydra-core",
        "pytorch-lightning==1.5.2",
        "jax",
        "jaxlib"
        ]

loftrs = ["pytorch-lightning==1.5.2"
            ]

omniglue = ["tensorflow"
            ] 

duster = ["huggingface_hub"]
all = ["image-matching-models[loftrs, omniglue, duster]"]
